Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "4096"
  end

  config.ssh.insert_key = false

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get -yq update
    # sudo apt-get -yq install python3-pip
  SHELL
end
