- name: Docker - Service
  systemd: name=docker state=started enabled=yes

- name: Docker - IP Forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
