---
- name: Lid - HandleLidSwitch
  lineinfile:
    path: /etc/systemd/logind.conf
    regexp: '^#?\s*HandleLidSwitch='
    line: 'HandleLidSwitch=ignore'
    create: yes
    backup: yes
  notify: Lid - Restart systemd-logind

- name: Lid - HandleLidSwitchDocked
  lineinfile:
    path: /etc/systemd/logind.conf
    regexp: '^#?\s*HandleLidSwitchDocked='
    line: 'HandleLidSwitchDocked=ignore'
    create: yes
    backup: yes
  notify: Lid - Restart systemd-logind

- name: Lid - HandleLidSwitchExternalPower
  lineinfile:
    path: /etc/systemd/logind.conf
    regexp: '^#?\s*HandleLidSwitchExternalPower='
    line: 'HandleLidSwitchExternalPower=ignore'
    create: yes
    backup: yes
  notify: Lid - Restart systemd-logind

- name: Lid - IgnoreLid
  lineinfile:
    path: /etc/UPower/UPower.conf
    regexp: '^#?\s*IgnoreLid='
    line: 'IgnoreLid=true'
    create: yes
    backup: yes
  notify: Lid - Restart upower
