sudo: required

services:
  - docker

script:
  - docker build -t altermarkive/lab-environment .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push altermarkive/lab-environment
