FROM balenalib/armv7hf-alpine:3.8

RUN [ "cross-build-start" ]

RUN apk add --update-cache tor torsocks openssh-client

RUN [ "cross-build-end" ]

ADD torrc /etc/tor/torrc
ADD entrypoint.sh /entrypoint.sh

VOLUME ["/var/lib/tor"]

ENTRYPOINT ["/bin/sh", "/entrypoint.sh"]
