- hosts: localhost
  gather_facts: False
  roles:
    - role: lid
      become: yes
    - role: docker
      become: yes
    - role: firewall
      become: yes
    - role: cups
      become: yes
    - role: nvidia
      become: yes
    - role: kubernetes
