---

- name: GitLab Server - Add systemd unit
  template:
    src: gitlab-server.service.j2
    dest: /etc/systemd/system/gitlab-server.service
    owner: root
    group: root
    mode: 0644
  register: gitlab_server_systemd_unit
