---
- name: Fonts - JetBrains Mono directory
  file:
    path: /usr/local/share/fonts/jetbrains_mono
    state: directory
    mode: "0755"

- name: Fonts - JetBrains Mono archive
  tempfile:
    state: file
    prefix: JetBrainsMono.
    suffix: .zip
  register: jetbrains_mono_zip

- name: Fonts - JetBrains Mono fetch
  get_url:
    url: https://download-cdn.jetbrains.com/fonts/JetBrainsMono-2.304.zip
    dest: "{{ jetbrains_mono_zip.path }}"
    force: true

- name: Fonts - JetBrains Mono installation
  command: unzip -f -j "{{ jetbrains_mono_zip.path }}" "fonts/ttf/*" -d /usr/local/share/fonts/jetbrains_mono

- name: Fonts - JetBrains Mono archive cleanup
  file:
    path: "{{ jetbrains_mono_zip.path }}"
    state: absent

- name: Fonts - DejaVu directory
  file:
    path: /usr/local/share/fonts/dejavu
    state: directory
    mode: "0755"

- name: Fonts - DejaVu archive
  tempfile:
    state: file
    prefix: DejaVuSans.
    suffix: .zip
  register: dejavu_zip

- name: Fonts - DejaVu fetch
  get_url:
    url: https://github.com/dejavu-fonts/dejavu-fonts/releases/download/version_2_37/dejavu-fonts-ttf-2.37.zip
    dest: "{{ dejavu_zip.path }}"
    force: true

- name: Fonts - DejaVu installation
  command: unzip -f -j "{{ dejavu_zip.path }}" "dejavu-fonts-ttf-2.37/ttf/DejaVuSans-Oblique.ttf" "dejavu-fonts-ttf-2.37/ttf/DejaVuSans-BoldOblique.ttf" -d /usr/local/share/fonts/dejavu

- name: Fonts - DejaVu archive cleanup
  file:
    path: "{{ dejavu_zip.path }}"
    state: absent

- name: Fonts - Reload
  command: fc-cache -f -v
