---
- name: git - Installation
  apt:
    pkg:
      - git
      - git-lfs
    state: latest
    update_cache: yes
  become: yes

- name: git - Scheduled git prefetch
  command: git maintenance start

- name: git - Accelerate git status
  shell: |
    git config --global core.fsmonitor true
    git config --global core.untrackedcache true
