Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
  Function:
    Type: AWS::Lambda::Function
    Properties:
      Description: EraseMe Node.js
      FunctionName: eraseme
      Code:
        ZipFile: |
          exports.handler = async (event, context) => {
            console.log("Hello Node.js!");
            console.log(JSON.stringify(event));
            return "{}";
          };

      Handler: index.handler
      MemorySize: 128
      Role: !GetAtt LambdaRole.Arn
      Runtime: nodejs10.x