Parameters:
  RepoUriParameter:
    Type: String
    Description: URI of the Docker image

Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
  Function:
    Type: AWS::Lambda::Function
    Properties:
      Description: EraseMe Dockerized Python
      FunctionName: eraseme
      Code:
        ImageUri:
          Ref: RepoUriParameter
      PackageType: Image
      MemorySize: 128
      Role: !GetAtt LambdaRole.Arn
