---
- name: Utilities - Hostname
  command: hostname
  register: hostname_output

- name: Utilities - Directories
  file:
    path: "/var/sovreign/{{ item }}"
    state: directory
    mode: 0700
  loop:
    - "etc"
    - "tailscale"
    - "coder"
    - "coder/config"
    - "coder/local"
  become: yes

- name: Utilities - Config
  copy:
    src: supervisord.conf
    dest: "/var/sovreign/etc/supervisord.conf"
    mode: 0600
  become: yes

- name: Utilities - Network
  community.docker.docker_network:
    name: sovreign-compute-utilities-network

- name: Utilities - Container
  community.docker.docker_container:
    name: sovreign-compute-utilities
    image: ghcr.io/altermarkive/sovreign-compute-utilities:latest
    pull: yes
    state: started
    restart_policy: always
    recreate: true
    hostname: "{{ hostname_output.stdout }}"
    networks:
      - name: sovreign-compute-utilities-network
    env:
      HOSTNAME: "{{ hostname_output.stdout }}"
      TS_AUTHKEY: "{{ tailscale_auth_key }}"
      UTILITIES_PASSWORD: "{{ utilities_password }}"
    command: ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]
    volumes:
      - "/var/sovreign/etc/supervisord.conf:/etc/supervisord.conf"
      - "/var/sovreign/tailscale:/var/run/tailscale"
      - "/var/sovreign/ssh:/root/.ssh"
      - "/var/sovreign/volume:/root/projects"
