---
- name: Docker - Prerequisites
  apt:
    pkg:
      - ca-certificates
    state: latest
    update_cache: yes

- name: Docker - Keyring
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Docker - GPG
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0664'

- name: Docker - Architecture
  command: dpkg --print-architecture
  register: dpkg_architecture_output

- name: Docker - Release
  command: lsb_release -cs 2> /dev/null
  register: lsb_release_output

- name: Docker - Repository
  apt_repository:
    repo: "deb [arch={{ dpkg_architecture_output.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ lsb_release_output.stdout }} stable"
    state: present

- name: Docker - Engine
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    update_cache: yes

- name: Docker - Group
  group: name=docker

- name: Docker - User
  user: name={{ lookup('ansible.builtin.env', 'USER') }} groups=docker append=yes

- name: Docker - Service
  systemd: name=docker state=started enabled=yes
