name: Automation Script

on: [push]

jobs:
  pipeline:
    name: Pipeline
    runs-on: ubuntu-20.04
    steps:
      - name: Initiating
        uses: actions/checkout@v2.4.0
      - name: Tags
        id: tags
        run: |
          DOCKER_IMAGE='ghcr.io/${{ github.actor }}/ssh-over-tor'
          TAGS="${DOCKER_IMAGE}:${{ github.sha }},${DOCKER_IMAGE}:latest"
          echo ::set-output name=tags::${TAGS}
      - name: QEMU
        uses: docker/setup-qemu-action@v1.2.0
      - name: Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.6.0
      - name: Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: ghcr.io
      - name: Build
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ${{ steps.tags.outputs.tags }}
