---
- name: Sound - Disable screenshot
  command:
    cmd: mv /usr/share/sounds/freedesktop/stereo/screen-capture.oga /usr/share/sounds/freedesktop/stereo/screen-capture.oga.disabled
    removes: /usr/share/sounds/freedesktop/stereo/screen-capture.oga
  become: true
