---
- name: Kubernetes - Prerequisites
  apt:
    pkg:
      - ca-certificates
      - gnupg
    state: latest
    update_cache: yes
  become: yes

- name: Kubernetes - kind
  get_url:
    url: https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64
    dest: /usr/local/bin/kind
    mode: '0755'
    force: true
  become: yes

- name: Kubernetes - Version
  uri:
    url: https://dl.k8s.io/release/stable.txt
    return_content: yes
  register: kubernetes_version

- name: Kubernetes - kubectl
  get_url:
    url: https://dl.k8s.io/release/{{ kubernetes_version.content }}/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: '0755'
    force: true
  become: yes

- name: Kubernetes - Check
  command: kind get clusters
  register: kind_clusters
  changed_when: false

- name: Kubernetes - Cluster
  command: kind create cluster --name sovereign-cluster
  when: "'sovereign-cluster' not in kind_clusters.stdout"
  args:
    creates: "{{ lookup('env','HOME') }}/.kube/config"

- name: Kubernetes - Verify
  command: kubectl cluster-info
  register: cluster_info

- name: Kubernetes - Show
  debug:
    msg: "{{ cluster_info.stdout }}"

- name: Kubernetes - Helm GPG
  get_url:
    url: https://packages.buildkite.com/helm-linux/helm-debian/gpgkey
    dest: /tmp/helm.gpg
    force: true

- name: Kubernetes - Helm GPG Dearmor
  command: gpg -o /usr/share/keyrings/helm-keyring.gpg --batch --yes --dearmor /tmp/helm.gpg
  become: yes

- name: Kubernetes - Helm Repository
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/helm-keyring.gpg] https://packages.buildkite.com/helm-linux/helm-debian/any/ any main
    state: present
  become: yes

- name: Kubernetes - Helm Upgrade
  apt:
    update_cache: yes
    upgrade: full
  become: yes

- name: Kubernetes - Helm
  apt:
    pkg:
      - helm
    state: latest
    update_cache: yes
  become: yes

- name: Kubernetes - Kueue
  kubernetes.core.helm:
    name: kueue
    chart_ref: oci://registry.k8s.io/kueue/charts/kueue
    release_namespace: kueue-system
    create_namespace: true
    wait: true
    state: present
