name: Automation Script

on: [push]

jobs:
  pipeline:
    name: Pipeline
    runs-on: ubuntu-20.04
    env:
      DOCKERHUB_USER: ${{ github.actor }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: QEMU
        uses: docker/setup-qemu-action@v1
      - name: Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Prepare
        id: prepare
        run: |
          DOCKER_IMAGE=${{ github.actor }}/${GITHUB_REPOSITORY#*/}
          VERSION=latest
          DESCRIBED=$(git describe --tags)
          TAGS="${DOCKER_IMAGE}:${VERSION},${DOCKER_IMAGE}:${DESCRIBED}"
          echo ::set-output name=tags::${TAGS}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm/v7
          tags: ${{ steps.prepare.outputs.tags }}
