---
- name: Utilities - Hostname
  command: hostname
  register: hostname_output

- name: Utilities - Directories
  file:
    path: "/var/sovereign/{{ item }}"
    state: directory
    mode: 0700
  loop:
    - "etc"
    - "tailscale"
    - "coder"
    - "coder/config"
    - "coder/local"

- name: Utilities - Config
  copy:
    src: supervisord.conf
    dest: "/var/sovereign/etc/supervisord.conf"
    mode: 0600

- name: Utilities - Network
  community.docker.docker_network:
    name: sovereign-compute-utilities-network

- name: Utilities - Container
  community.docker.docker_container:
    name: sovereign-compute-utilities
    image: ghcr.io/altermarkive/sovereign-compute-utilities:latest
    pull: yes
    state: started
    restart_policy: always
    recreate: true
    hostname: "{{ hostname_output.stdout }}"
    networks:
      - name: sovereign-compute-utilities-network
    env:
      HOSTNAME: "{{ hostname_output.stdout }}"
      TS_AUTHKEY: "{{ tailscale_auth_key }}"
      UTILITIES_PASSWORD: "{{ utilities_password }}"
    command: ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]
    volumes:
      - "/var/sovereign/etc/supervisord.conf:/etc/supervisord.conf"
      - "/var/sovereign/tailscale:/var/run/tailscale"
      - "/var/sovereign/ssh:/root/.ssh"
      - "/var/sovereign/volume:/root/projects"

- name: Utilities - Files
  community.docker.docker_container:
    name: sovereign-compute-filebrowser
    image: filebrowser/filebrowser:latest
    pull: yes
    state: started
    restart_policy: always
    recreate: true
    networks:
      - name: sovereign-compute-utilities-network
    # ports:
    #   - "9090:80"
    command: ["--username", "user", "--password", "{{ utilities_password | password_hash('bcrypt') }}", "--disable-exec"]
    volumes:
      - "/var/sovereign/volume/quarantine:/srv"
