- name: Let's Encrypt - Create directory for the certificate
  file:
    path: /var/www/letsencrypt
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Let's Encrypt - Install epel repository
  yum: name=epel-release state=present

- name: Let's Encrypt - Enable rhui extras channel
  command: yum-config-manager --enable rhui-REGION-rhel-server-extras rhui-REGION-rhel-server-optional

- name: Let's Encrypt - Install
  yum: name=certbot state=latest

- name: Let's Encrypt - Create the certificate
  shell: certbot certonly -m {{ gitlab_server_email }} --agree-tos --standalone -w /var/www/letsencrypt -d {{ gitlab_server_fqdn }}
  args:
    creates: /etc/letsencrypt/live/{{ gitlab_server_fqdn }}

- name: Let's Encrypt - Add the cronjob for the certificate renewal
  cron:
    special_time: monthly
    job: "systemdctl stop gitlab-server.service && certbot renew && systemdctl stop gitlab-server.service"
