---
- name: Lid - Restart systemd-logind
  debug:
    msg: The lid switch settings will take effect after a reboot (to avoid disrupting Ansible)
  # systemd:
  #   name: systemd-logind
  #   state: restarted
  #   daemon_reload: yes

- name: Lid - Restart upower
  systemd:
    name: upower
    state: restarted
    daemon_reload: yes
