---

- name: Docker CE - Add the yum repository
  yum_repository:
    name: docker-ce-stable
    file: docker
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    enabled: yes
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: Docker CE - Create the group
  group: name=docker

- name: Docker CE - Install
  yum: name=docker-ce state=installed

- name: Docker CE - Add Ansible user to the group
  user: name={{ ansible_user }} groups=docker append=yes
