---
- name: Firewall - Package
  apt:
    pkg:
      - ufw
    state: latest
    update_cache: yes
  become: yes

- name: Firewall - Enabled
  community.general.ufw:
    state: enabled
    policy: deny
    direction: incoming
  become: yes
