---

- name: GitLab CI Runner - List runners
  shell: docker exec gitlab-ci-runner gitlab-runner list 2>&1
  register: configured_runners
  changed_when: False

- name: GitLab CI Runner - Register runner
  command: docker exec gitlab-ci-runner \
    gitlab-runner register \
    --non-interactive \
    --url '{{ gitlab_ci_runner_url }}' \
    --registration-token '{{ gitlab_ci_runner_token }}' \
    --description '{{ ansible_hostname }}' \
    --tag-list 'docker' \
    --executor 'docker' \
    --run-untagged=True \
    --docker-image 'docker:latest' \
    --docker-volumes /var/run/docker.sock:/var/run/docker.sock \
    --docker-volumes /root/.docker/config.json:/root/.docker/config.json:ro
  when: configured_runners.stdout.find('\n' + ansible_hostname + ' ') == -1
