name: Build autossh

on: [push]

jobs:
  pipeline:
    name: Pipeline
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Tags
        id: tags
        run: |
          DOCKER_IMAGE=${{ github.actor }}/autossh
          TAGS="${DOCKER_IMAGE}:${GITHUB_SHA},${DOCKER_IMAGE}:latest"
          echo ::set-output name=tags::${TAGS}
      - name: QEMU
        uses: docker/setup-qemu-action@v1.1.0
      - name: Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.3.0
      - name: Login
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v2.4.0
        with:
          context: autossh
          push: true
          platforms: linux/386,linux/amd64,linux/arm64/v8,linux/arm/v7,linux/arm/v6,linux/ppc64le,linux/s390x
          tags: ${{ steps.tags.outputs.tags }}
