---
name: CI
on: [push, pull_request]
permissions:
  contents: read
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Check formatting
        run: test -z "$(gofmt -l .)"
      - name: Check linting
        run: go vet ./...
      - name: Check tests
        run: go test ./...
