---
name: Dependabot Auto-merge
on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: write
  pull-requests: write
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: Dependabot PR - Metadata
        id: metadata
        uses: dependabot/fetch-metadata@v3.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Dependabot PR - Approve and Auto-merge
        # Uncomment to restrict dependabot auto-merge to just GitHub Actions
        # if: steps.metadata.outputs.package-ecosystem == 'github_actions' || steps.metadata.outputs.dependency-group == 'all-deps'
        # Note Go to Settings → General → Pull Requests and check "Allow auto-merge"
        run: |
          gh pr review "$PR_URL" --approve
          gh pr merge "$PR_URL" --auto --squash --delete-branch
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
