name: Automation for httpd-reloadable-openid

on: [push]

jobs:
  pipeline:
    name: Pipeline
    runs-on: ubuntu-20.04
    steps:
      - name: Tags
        id: tags
        run: |
          VERSION=$(curl -L -s 'https://registry.hub.docker.com/v2/repositories/library/httpd/tags?page_size=1000000' | jq -r '."results"[]["name"]' | grep "2\..*\..*\-alpine" | sort | tail -1)
          DOCKER_IMAGE='ghcr.io/${{ github.actor }}/httpd-reloadable-openid'
          TAGS="${DOCKER_IMAGE}:${VERSION},${DOCKER_IMAGE}:latest"
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=tags::${TAGS}
      - name: Initiating
        uses: actions/checkout@v3.0.2
      - name: QEMU
        uses: docker/setup-qemu-action@v2.0.0
      - name: Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.0.0
      - name: Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: ghcr.io
      - name: Build
        uses: docker/build-push-action@v3.0.0
        with:
          build-args: |
            VERSION=${{ steps.tags.outputs.version }}
          context: azure/apache-reverse-proxy-lets-encrypt-aad
          push: true
          platforms: linux/386,linux/amd64
          tags: ${{ steps.tags.outputs.tags }}
