name: Build imagemagick

on:
  schedule:
    - cron: '0 0 1 * *'
  push:

jobs:
  pipeline:
    name: Pipeline
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Tags
        id: tags
        run: |
          DOCKER_IMAGE='ghcr.io/${{ github.actor }}/imagemagick'
          TAGS="${DOCKER_IMAGE}:$(date +%Y%m%d%H%M%S),${DOCKER_IMAGE}:latest"
          echo ::set-output name=tags::${TAGS}
      - name: QEMU
        uses: docker/setup-qemu-action@v2.0.0
      - name: Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.0.0
      - name: Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: ghcr.io
      - name: Build
        uses: docker/build-push-action@v3.1.0
        with:
          context: imagemagick
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: ${{ steps.tags.outputs.tags }}
