name: Build autossh

on: [push]

jobs:
  pipeline:
    name: Pipeline
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Tags
        id: tags
        run: |
          DOCKER_IMAGE='ghcr.io/${{ github.actor }}/python-data-experiments'
          TAGS="${DOCKER_IMAGE}:latest"
          echo ::set-output name=tags::${TAGS}
      - name: QEMU
        uses: docker/setup-qemu-action@v2.1.0
      - name: Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.5.0
      - name: Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: ghcr.io
      - name: Build
        uses: docker/build-push-action@v4.0.0
        with:
          context: data-experiments
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: ${{ steps.tags.outputs.tags }}
