name: Automation for sovereign-compute-utilities

on: [push]

jobs:
  pipeline:
    name: Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Tags
        id: tags
        run: |
          DOCKER_IMAGE='ghcr.io/${{ github.actor }}/sovereign-compute-utilities'
          TAGS="${DOCKER_IMAGE}:latest,${DOCKER_IMAGE}:${{ github.sha }}"
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT
      - name: QEMU
        uses: docker/setup-qemu-action@v3
      - name: Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Login
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
          registry: ghcr.io
      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: sovereign-utilities
          push: true
          platforms: linux/amd64
          tags: ${{ steps.tags.outputs.tags }}
      - name: Trash
        uses: actions/delete-package-versions@v5
        with:
          min-versions-to-keep: 10
          package-name: sovereign-compute-utilities
          package-type: container
