---
name: GitHub Super-Linter

on: [push]

jobs:
  pipeline:
    name: Pipeline
    runs-on: ubuntu-22.04
    steps:
      - name: Initiating
        uses: actions/checkout@v4
      - name: GitHub Super-Linter
        uses: super-linter/super-linter@v6
        env:
          DISABLE_ERRORS: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
