---
name: GitHub Super-Linter

on: [push]

jobs:
  pipeline:
    name: Pipeline
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: Initiating
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: GitHub Super-Linter
        uses: super-linter/super-linter@v6
        env:
          DISABLE_ERRORS: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
