name: Build svetovit

on: [push]

jobs:
  pipeline:
    name: Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Tags  # To have versioned TAG add: ,${DOCKER_IMAGE}:${{ github.sha }}
        id: tags
        run: |
          DOCKER_IMAGE='ghcr.io/${{ github.repository_owner }}/svetovit'
          TAGS="${DOCKER_IMAGE}:latest"
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT
      - name: QEMU
        uses: docker/setup-qemu-action@v3
      - name: Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Login
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
          registry: ghcr.io
      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: svetovit
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: ${{ steps.tags.outputs.tags }}
